person:
     lastName: zhangshan
     age: 18
     boss: false
     birth: 2017/12/12
     maps: {k1: 11,k2: 12}
     list:
       - lisi
       - zhaoliu
     dog:
        name: xiaogou
        age: 2